# Generated by Django 5.2.6 on 2026-05-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('image', models.TextField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('current_page', models.IntegerField(default=0)),
                ('total_pages', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
